// flow-typed signature: 801df1567198bbaeb773f30d8115caaf
// flow-typed version: <<STUB>>/openmined-ui_v^0.0.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openmined-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'openmined-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openmined-ui/flow-typed/npm/react-helmet_v3.x.x' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/async/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/background-gradient/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/button/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/grid/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/heading/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/input/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/page/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/progress/index' {
  declare module.exports: any;
}

declare module 'openmined-ui/lib/switch/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openmined-ui/flow-typed/npm/react-helmet_v3.x.x.js' {
  declare module.exports: $Exports<'openmined-ui/flow-typed/npm/react-helmet_v3.x.x'>;
}
declare module 'openmined-ui/lib/async/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/async/index'>;
}
declare module 'openmined-ui/lib/background-gradient/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/background-gradient/index'>;
}
declare module 'openmined-ui/lib/button/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/button/index'>;
}
declare module 'openmined-ui/lib/grid/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/grid/index'>;
}
declare module 'openmined-ui/lib/heading/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/heading/index'>;
}
declare module 'openmined-ui/lib/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/index'>;
}
declare module 'openmined-ui/lib/input/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/input/index'>;
}
declare module 'openmined-ui/lib/page/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/page/index'>;
}
declare module 'openmined-ui/lib/progress/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/progress/index'>;
}
declare module 'openmined-ui/lib/switch/index.js' {
  declare module.exports: $Exports<'openmined-ui/lib/switch/index'>;
}
